version: '3.9'

services:
  nyxbot:
    container_name: nyxbot
    restart: unless-stopped
    image: kingprimes/nyxbot:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
#      - ./DataSource:/app/DataSource
#      - ./logs:/app/logs
#      - ./locate.yaml:/app/locate.yaml