test:
  isTest: false

spring:
  security:
    user:
      name: admin
      password: 123456
      roles:
        - user
        - admin
  mvc:
    static-path-pattern: /static/**

shiro:
  ws-config:
    ws-url: /nyx