test:
  isTest: true

async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 5
      queue_capacity: 80
      name:
        prefix: async-

spring:

  mvc:
    static-path-pattern: /static/**
  #数据源配置
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    #设置数据源；MODE=MySQL 可以解析MySQL形式的SQL语句
    url: jdbc:h2:file:./data/H2;MODE=MySQL
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false

  #缓存设置
  cache:
    type: cache2k

shiro:
  ws-config:
    ws-url: /nyx