name: Generate Release Draft

on:
  push:
    branches:
      - main  # 或者您的默认分支
  pull_request:
    types:
      - closed

jobs:
  generate_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 使用release-drafter创建或更新发布草稿
      - name: Create or update release draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
