name: Sync Releases to Git

on:
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - debug
          - info
          - warning
          - error
jobs:
  gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Sync Release to Gitee
        env:
          GH_TOKEN: ${{ github.token }}
          GITEE_REPO: https://gitee.com/KingPrime/NyxBot.git
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          sudo apt install gh
          gh repo clone ${GITEE_REPO} -u King
          gh release create v$VERSION -t ${GITEE_REPO} -n "Release $VERSION" ${{ github.event.release.tag_name }}
  gitcode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Sync Release to GitCode
        env:
          GH_TOKEN: ${{ github.token }}
          GITCODE_REPO: https://gitcode.com/KingPrimes/NyxBot.git
          GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}
        run: |
          sudo apt install gh
          gh repo clone ${GITCODE_REPO} -u King
          gh release create v$VERSION -t ${GITCODE_REPO} -n "Release $VERSION" ${{ github.event.release.tag_name }}