name: Test Build Release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - debug
          - info
          - warning
          - error
jobs:
  build-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kingprimes.top
          path: target/NyxBot.jar
          if-no-files-found: warn
          retention-days: 30
          compression-level: 6
          overwrite: true
      - name: Upload JAR to another repository
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/KingPrimes/kingprimes.github.io.git
          mkdir -p kingprimes.github.io/static/data/nyxbot
          cp target/NyxBot.jar kingprimes.github.io/static/data/nyxbot/
          cd kingprimes.github.io
          git add -f static/data/nyxbot/NyxBot.jar
          git commit -m "Add NyxBot.jar to static/data/nyxbot"
          git push